server:
  servlet:
    context-path: /api-cadastro
  port: 9090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pdv
    username: sa
    password: sa